// Code generated by mockery v2.39.0. DO NOT EDIT.

package mocks

// GetRollupId provides a mock function with given fields:
func (_m *Etherman) GetRollupId() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRollupId")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}